package com.ustb.bean;

import com.fasterxml.jackson.annotation.JsonProperty;

public class ChainParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chain_param.SYS_ID
     *
     * @mbggenerated
     */
    private Integer sysId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chain_param.CHAIN_NAME
     *
     * @mbggenerated
     */
    private String chainName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chain_param.CHAIN_IP
     *
     * @mbggenerated
     */
    private String chainIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chain_param.CHAIN_PORT
     *
     * @mbggenerated
     */
    private String chainPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chain_param.CHAIN_RPC_PORT
     *
     * @mbggenerated
     */
    private String chainRpcPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chain_param.CHAIN_TYPE
     *
     * @mbggenerated
     */
    private Integer chainType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chain_param.CHAIN_USERNAME
     *
     * @mbggenerated
     */
    private String chainUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chain_param.CHAIN_PASSWORD
     *
     * @mbggenerated
     */
    private String chainPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chain_param.MAIN_ADDRESS
     *
     * @mbggenerated
     */
    private String mainAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chain_param.IS_USED
     *
     * @mbggenerated
     */
    private Boolean isUsed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chain_param.IS_Main
     *
     * @mbggenerated
     */

    private Boolean isMain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chain_param.SYS_Id
     *
     * @return the value of chain_param.SYS_Id
     *
     * @mbggenerated
     */
    public Integer getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chain_param.SYS_ID
     *
     * @param sysId the value for chain_param.SYS_ID
     *
     * @mbggenerated
     */
    public void setSysId(Integer sysId) {
        this.sysId = sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chain_param.CHAIN_NAME
     *
     * @return the value of chain_param.CHAIN_NAME
     *
     * @mbggenerated
     */
    public String getChainName() {
        return chainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chain_param.CHAIN_NAME
     *
     * @param chainName the value for chain_param.CHAIN_NAME
     *
     * @mbggenerated
     */
    public void setChainName(String chainName) {

        this.chainName = chainName == null ? null : chainName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chain_param.CHAIN_IP
     *
     * @return the value of chain_param.CHAIN_IP
     *
     * @mbggenerated
     */
    public String getChainIp() {
        return chainIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chain_param.CHAIN_IP
     *
     * @param chainIp the value for chain_param.CHAIN_IP
     *
     * @mbggenerated
     */
    public void setChainIp(String chainIp) {
        this.chainIp = chainIp == null ? null : chainIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chain_param.CHAIN_PORT
     *
     * @return the value of chain_param.CHAIN_PORT
     *
     * @mbggenerated
     */
    public String getChainPort() {
        return chainPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chain_param.CHAIN_PORT
     *
     * @param chainPort the value for chain_param.CHAIN_PORT
     *
     * @mbggenerated
     */
    public void setChainPort(String chainPort) {
        this.chainPort = chainPort == null ? null : chainPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chain_param.CHAIN_RPC_PORT
     *
     * @return the value of chain_param.CHAIN_RPC_PORT
     *
     * @mbggenerated
     */
    public String getChainRpcPort() {
        return chainRpcPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chain_param.CHAIN_RPC_PORT
     *
     * @param chainRpcPort the value for chain_param.CHAIN_RPC_PORT
     *
     * @mbggenerated
     */
    public void setChainRpcPort(String chainRpcPort) {
        this.chainRpcPort = chainRpcPort == null ? null : chainRpcPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chain_param.CHAIN_TYPE
     *
     * @return the value of chain_param.CHAIN_TYPE
     *
     * @mbggenerated
     */
    public Integer getChainType() {
        return chainType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chain_param.CHAIN_TYPE
     *
     * @param chainType the value for chain_param.CHAIN_TYPE
     *
     * @mbggenerated
     */
    public void setChainType(Integer chainType) {
        this.chainType = chainType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chain_param.CHAIN_USERNAME
     *
     * @return the value of chain_param.CHAIN_USERNAME
     *
     * @mbggenerated
     */
    public String getChainUsername() {
        return chainUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chain_param.CHAIN_USERNAME
     *
     * @param chainUsername the value for chain_param.CHAIN_USERNAME
     *
     * @mbggenerated
     */
    public void setChainUsername(String chainUsername) {
        this.chainUsername = chainUsername == null ? null : chainUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chain_param.CHAIN_PASSWORD
     *
     * @return the value of chain_param.CHAIN_PASSWORD
     *
     * @mbggenerated
     */
    public String getChainPassword() {
        return chainPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chain_param.CHAIN_PASSWORD
     *
     * @param chainPassword the value for chain_param.CHAIN_PASSWORD
     *
     * @mbggenerated
     */
    public void setChainPassword(String chainPassword) {
        this.chainPassword = chainPassword == null ? null : chainPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chain_param.MAIN_ADDRESS
     *
     * @return the value of chain_param.MAIN_ADDRESS
     *
     * @mbggenerated
     */
    public String getMainAddress() {
        return mainAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chain_param.MAIN_ADDRESS
     *
     * @param mainAddress the value for chain_param.MAIN_ADDRESS
     *
     * @mbggenerated
     */
    public void setMainAddress(String mainAddress) {
        this.mainAddress = mainAddress == null ? null : mainAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chain_param.IS_USED
     *
     * @return the value of chain_param.IS_USED
     *
     * @mbggenerated
     */
    @JsonProperty(value = "isUsed")
    public Boolean getUsed() {
        return isUsed;
    }

    public void setUsed(Boolean used) {
        this.isUsed = used;
    }

    @JsonProperty(value = "isMain")
    public Boolean getMain() {
        return isMain;
    }

    public void setMain(Boolean main) {
        this.isMain = main;
    }

    public ChainParam() {
    }

    public ChainParam(String chainName, String chainIp, String chainPort, String chainRpcPort, Integer chainType, String chainUsername, String chainPassword, String mainAddress, Boolean isUsed, Boolean isMain) {
        this.chainName = chainName;
        this.chainIp = chainIp;
        this.chainPort = chainPort;
        this.chainRpcPort = chainRpcPort;
        this.chainType = chainType;
        this.chainUsername = chainUsername;
        this.chainPassword = chainPassword;
        this.mainAddress = mainAddress;
        this.isUsed = isUsed;
        this.isMain = isMain;
    }
    public ChainParam(Integer sysId, String chainName, String chainIp, String chainPort, String chainRpcPort, Integer chainType, String chainUsername, String chainPassword, String mainAddress, Boolean isUsed, Boolean isMain) {
        this.sysId = sysId;
        this.chainName = chainName;
        this.chainIp = chainIp;
        this.chainPort = chainPort;
        this.chainRpcPort = chainRpcPort;
        this.chainType = chainType;
        this.chainUsername = chainUsername;
        this.chainPassword = chainPassword;
        this.mainAddress = mainAddress;
        this.isUsed = isUsed;
        this.isMain = isMain;
    }
    public ChainParam(Integer sysId, String chainName, String chainIp, String chainPort, String chainRpcPort, Integer chainType, String chainUsername, String chainPassword, String mainAddress) {
        this.sysId = sysId;
        this.chainName = chainName;
        this.chainIp = chainIp;
        this.chainPort = chainPort;
        this.chainRpcPort = chainRpcPort;
        this.chainType = chainType;
        this.chainUsername = chainUsername;
        this.chainPassword = chainPassword;
        this.mainAddress = mainAddress;
    }
    public ChainParam(Integer sysid,String chainName, String chainIp, String chainPort, String chainUsername, String chainPassword){
        this.sysId = sysid;
        this.chainName = chainName;
        this.chainIp = chainIp;
        this.chainRpcPort = chainPort;
        this.chainUsername = chainUsername;
        this.chainPassword = chainPassword;
    }
}